In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences= ['Hello How is the weather today','Why MJ whent for baseball',
           'MJ or Lebron the Greatest of all time','What are the current affairs',
           'working on natural language processing','i am a good developer']

In [3]:
sentences

['Hello How is the weather today',
 'Why MJ whent for baseball',
 'MJ or Lebron the Greatest of all time',
 'What are the current affairs',
 'working on natural language processing',
 'i am a good developer']

In [4]:
# vocabulary size
voc_size=10000

In [6]:
one_hot_repr=  [one_hot(words,voc_size)for words in sentences]
print(one_hot_repr)

[[855, 8079, 3503, 9548, 1228, 2883], [6059, 9155, 5355, 1275, 3363], [9155, 8969, 9903, 9548, 8844, 656, 3918, 8408], [1725, 8976, 9548, 5127, 6223], [3919, 2975, 2784, 7001, 6736], [2611, 6370, 8239, 4251, 1126]]


In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
sent_length=8
pad_sent= pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(pad_sent)

[[   0    0  855 8079 3503 9548 1228 2883]
 [   0    0    0 6059 9155 5355 1275 3363]
 [9155 8969 9903 9548 8844  656 3918 8408]
 [   0    0    0 1725 8976 9548 5127 6223]
 [   0    0    0 3919 2975 2784 7001 6736]
 [   0    0    0 2611 6370 8239 4251 1126]]


In [13]:
dim= 15

In [15]:
model= Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 15)             150000    
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
print(model.predict(pad_sent))

[[[-0.04699528 -0.00503821 -0.03128604  0.02764037 -0.03162359
    0.00997094  0.03317318  0.04297104 -0.01939085  0.04708963
   -0.04130446  0.03446381 -0.04519634  0.00763839 -0.03392925]
  [-0.04699528 -0.00503821 -0.03128604  0.02764037 -0.03162359
    0.00997094  0.03317318  0.04297104 -0.01939085  0.04708963
   -0.04130446  0.03446381 -0.04519634  0.00763839 -0.03392925]
  [ 0.00626676  0.01533207 -0.04621675  0.04746139 -0.03799584
   -0.01512539  0.02729077 -0.01459272 -0.00970439 -0.04839526
    0.03452632 -0.04546333  0.01620356  0.01627399 -0.04719725]
  [-0.03695088 -0.02187265 -0.04921861  0.00498073  0.02817355
   -0.03646337 -0.04691195  0.02000202  0.0418884   0.04203106
    0.04700417  0.02825967 -0.04207736  0.00867196 -0.04633204]
  [-0.04743544 -0.00871575 -0.02210368  0.02261615  0.04581026
   -0.04319206 -0.01889248 -0.03162413  0.01097795 -0.04760638
    0.04165843  0.03483964 -0.04919816  0.04205826  0.03624943]
  [-0.02426746 -0.03751502 -0.04278687  0.00316508